### ISSUE TITLE
Tjoy and number of button

### ISSUE THREAD

**Issue by JeanChristophe24** [mpaperno/TJoy#7]
He,

I am new to TOUCH PORTAL and TJOY PLUGIN.
I don't know how to configure the software and its plugin in order to access
to the 128 buttons of Vjoy, I only have 64 buttons as shown in the screenshot.

Thanks for your work

![Capture d'écran 2023-11-16 082507](https://github.com/mpaperno/TJoy/assets/151126529/ba85554e-f420-4fa7-a06b-667ea428488b)
![Capture d'écran 2023-11-16 082851](https://github.com/mpaperno/TJoy/assets/151126529/8ed673e8-e8c9-4b95-82c9-2a6d365f734f)
![Capture d'écran 2023-11-16 083032](https://github.com/mpaperno/TJoy/assets/151126529/b5c28c2f-ad72-4c0a-8fd5-d97ce929714d)

Touch Portal version 4.0 build 1
Tjoy Touch Portal plugin version 1010000
Vjoy version 2.1.9
Windows 11
IPAD PRO IPIOS 17.1

**Comment by mpaperno** [comment]
Hello!

I'm replying on Discord also, but in case you don't see that or someone else finds this useful later...

It does seem to work here, so I'm not sure what the problem may be.

![image](https://github.com/mpaperno/TJoy/assets/1366615/62a52cd2-aded-4ad8-baab-91c0554c300a)

Sometimes it's just the list of buttons hasn't been updated in the TP interface yes... You can try selecting another vJoy device from the first option box and then selecting "vJoy 2" again... that should update the list of buttons in the TP interface, in case that's the issue (maybe you had 64 buttons at one point?).

It should all work even if you change the button count w/out restarting the plugin.  That's what I just tested.  Though I made sure I wasn't connected to that vJoy device with the plugin before I changed the button count.

**Comment by mpaperno** [comment]
Solved by re-connecting plugin to vJoy device after changing number of buttons.
